import { Inter } from "next/font/google";

import Navbar from "@/components/Navbar";

import type { Metadata } from "next";
import type { ReactNode } from "react";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "NextAuth Demo"
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="flex justify-center items-start p-6 min-h-screen">{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
